default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
    python: python3.10

ci:
    skip:
        - shelf-commit-msg
    autofix_commit_msg: |
        🚧 [pre-commit.ci] auto fixes from pre-commit.com hooks
    autofix_prs: true
    autoupdate_schedule: weekly
    autoupdate_commit_msg: |
        🚧 [pre-commit.ci] pre-commit autoupdate

repos:
-   repo: https://github.com/korawica/clishelf
    rev: v0.2.3
    hooks:
    -   id: shelf-commit-msg
